### ISSUE TITLE
how to add slave  dns  nameserver ?

### ISSUE THREAD

**Issue by w796933** [NiclasHedam/vesta-dns#1]
sir . how to add slave  dns  nameserver ?

**Comment by NiclasHedam** [comment]
Start out by booting up an instance of this repository
```
docker run \
--name vesta-dns \
-e ADMIN_PASSWORD=password \
-p 8083:8083 \
-p 53:53 \
-p 53:53/udp \
-d niclashedam/vesta-dns
```

Connect the slave on the master server with

`v-add-remote-dns-host HOST PORT USER PASSWORD [TYPE] [DNS_USER]`

As far as I remember, you also need to add the following cron job to automate the sync.
`sudo /usr/local/vesta/bin/v-update-sys-queue dns-cluster`
